apiVersion: apps/v1
kind: Deployment
metadata:
  name: sba.kubernetes-cluster-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sba.kubernetes-cluster-app
  template:
    metadata:
      labels:
        app: sba.kubernetes-cluster-app
  spec:
    containers:
    - name: sba.kubernetes-cluster-container
      image: rangeley826/sba.kubernetes-cluster
      ports:
      - containerPort: 8226

---
apiVersion: v1
kind: Service
metadata:
  name: sba.kubernetes-cluster-service
spec:
  type: NodePort
  selector:
    app:  sba.kubernetes-cluster-app
  ports:
  - protocol: TCP
    port: 8226
    targetPort: 8226

