apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbaflaskapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sbaflaskapp
  template:
    metadata:
      labels:
        app: sbaflaskapp
    spec:
      containers:
      - name: sbaflaskapp
        image: rangeley826/sbaflaskapp
        ports:
        - containerPort: 8226

---
apiVersion: v1
kind: Service
metadata:
  name: sbaflaskapp-service
spec:
  type: NodePort
  selector:
    app:  sbaflaskapp
  ports:
  - protocol: TCP
    port: 8226
    targetPort: 8226
    nodePort: 30008
